name: Trigger API Tests
on:
  push:
    branches: [ oe-2 ]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Tests Repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_TEST_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ secrets.TEST_REPO_OWNER }}/${{ secrets.TEST_REPO_NAME }}/dispatches \
            -d '{"event_type":"web_app_push","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}","repository":"${{ github.repository }}"}}'
